### ISSUE TITLE
KEY_ERROR on postgres.py

### ISSUE THREAD

**Issue by KoalaGeo** [BritishGeologicalSurvey/pygeoapi#13]
**Description**
Pygeoapi won't start - using `docker pull ghcr.io/britishgeologicalsurvey/pygeoapi:latest` which implements https://github.com/geopython/pygeoapi/pull/964

```
START /entrypoint.sh
Trying to generate openapi.yml
Traceback (most recent call last):
  File "/pygeoapi/pygeoapi/provider/postgresql.py", line 260, in _get_engine_and_table_model
    table_model = _TABLE_MODEL_STORE[table_model_store_key]
KeyError: ('kwdmzpostgresql.ad.nerc.ac.uk', 5432, 'oraetl', 'ql_map_title_wgs84_off1m')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pygeoapi/pygeoapi/provider/postgresql.py", line 278, in _reflect_table_model
    metadata.reflect(schema=schema, only=[self.table], views=True)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/schema.py", line 4876, in reflect
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Could not reflect: requested table(s) not available in Engine(postgresql+psycopg2://oraetl_reader:***@kwdmzpostgresql.ad.nerc.ac.uk:5432/oraetl) schema 'public': (ql_map_title_wgs84_off1m)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pygeoapi", line 11, in <module>
    load_entry_point('pygeoapi', 'console_scripts', 'pygeoapi')()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1134, in __call__
    return self.main(*args, **kwargs)
      rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1665, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1665, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1401, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 767, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/pygeoapi/pygeoapi/openapi.py", line 1160, in generate
    content = yaml.safe_dump(get_oas(s), default_flow_style=False)
  File "/pygeoapi/pygeoapi/openapi.py", line 1113, in get_oas
    return get_oas_30(cfg)
  File "/pygeoapi/pygeoapi/openapi.py", line 477, in get_oas_30
    p = load_plugin('provider', get_provider_by_type(
  File "/pygeoapi/pygeoapi/plugin.py", line 108, in load_plugin
    plugin = class_(plugin_def)
  File "/pygeoapi/pygeoapi/provider/postgresql.py", line 100, in __init__
    self._engine, self.table_model = self._get_engine_and_table_model()
  File "/pygeoapi/pygeoapi/provider/postgresql.py", line 262, in _get_engine_and_table_model
    table_model = self._reflect_table_model(engine)
  File "/pygeoapi/pygeoapi/provider/postgresql.py", line 286, in _reflect_table_model
    raise ProviderQueryError(msg)
pygeoapi.provider.base.ProviderQueryError: Table 'ql_map_title_wgs84_off1m' not found in schema 'public' on postgresql+psycopg2://oraetl_reader:***@kwdmzpostgresql.ad.nerc.ac.uk:5432/oraetl.
ERROR: openapi.yml could not be generated ERROR
```

**Steps to Reproduce**
Run in GitLab using BGS config

**Expected behavior**
Connect to postgres & startup

**Environment**
docker pull ghcr.io/britishgeologicalsurvey/pygeoapi:latest

**Comment by ximenesuk** [comment]
The `KeyError` is intentional here, it's thrown if the key isn't already in the dictionary and so triggers the code in the `except` block. That is subsequently throwing an error in line 278:
```
metadata.reflect(schema=schema, only=[self.table], views=True)
```
due to the table not being found in the schema:
```
Table 'ql_map_title_wgs84_off1m' not found in schema 'public' on postgresql+psycopg2://oraetl_reader:***@kwdmzpostgresql.ad.nerc.ac.uk:5432/oraetl
```
That the schema being checked is 'public' implies either that 'public' is intended, or that the 'search_path' is not set in the config. 'search_path` should be a list of schemas, e.g. 'search_path': ['osm', 'public']. The first one is used by this provider.

This may be an issue if there is some config problem?

See the conversation on Teams, this may be an internal deployment issue on gitlab.

**Comment by volcan01010** [comment]
Put the schema that the table is in first in the list in the config, before "public". We could probably have a more informative error message.

**Comment by KoalaGeo** [comment]
Working now using `search_path: [published]`

However led to new issue but seems to be layer specific:

```
START /entrypoint.sh
Trying to generate openapi.yml
Traceback (most recent call last):
   File "/usr/lib/python3/dist-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 199, in represent_list
    return self.represent_sequence('tag:yaml.org,2002:seq', data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 92, in represent_sequence
    node_item = self.represent_data(item)
.......
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 58, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 231, in represent_undefined
    raise RepresenterError("cannot represent an object", data)
yaml.representer.RepresenterError: ('cannot represent an object', 'landslide_number')
ERROR: openapi.yml could not be generated ERROR
```

**Comment by KoalaGeo** [comment]
Closing will make new issue with representer error
